// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package project.manager;

public interface successOrBuilder extends
    // @@protoc_insertion_point(interface_extends:success)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string task = 1;</code>
   */
  java.lang.String getTask();
  /**
   * <code>string task = 1;</code>
   */
  com.google.protobuf.ByteString
      getTaskBytes();
}
