// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package project.manager;

public interface taskMatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taskMatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 working_day = 1;</code>
   */
  long getWorkingDay();

  /**
   * <code>int64 working_month = 2;</code>
   */
  long getWorkingMonth();

  /**
   * <code>int64 working_year = 3;</code>
   */
  long getWorkingYear();

  /**
   * <code>float number_of_hours = 4;</code>
   */
  float getNumberOfHours();

  /**
   * <code>int64 card_number = 5;</code>
   */
  long getCardNumber();
}
