// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutomatedSchedulingApp.proto

package grpc.CA1.AutomatedSchedulingApp;

public interface absenceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:absenceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 card_number = 1;</code>
   */
  int getCardNumber();

  /**
   * <code>int32 job_number = 2;</code>
   */
  int getJobNumber();

  /**
   * <code>float hours_booked = 3;</code>
   */
  float getHoursBooked();

  /**
   * <code>int32 day_booked = 4;</code>
   */
  int getDayBooked();

  /**
   * <code>int32 month_booked = 5;</code>
   */
  int getMonthBooked();

  /**
   * <code>int32 year_booked = 6;</code>
   */
  int getYearBooked();
}
