// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AutomatedSchedulingApp.proto

package grpc.CA1.AutomatedSchedulingApp;

/**
 * Protobuf type {@code absenceRequest}
 */
public  final class absenceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:absenceRequest)
    absenceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use absenceRequest.newBuilder() to construct.
  private absenceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private absenceRequest() {
    cardNumber_ = 0;
    jobNumber_ = 0;
    hoursBooked_ = 0F;
    dayBooked_ = 0;
    monthBooked_ = 0;
    yearBooked_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private absenceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            cardNumber_ = input.readInt32();
            break;
          }
          case 16: {

            jobNumber_ = input.readInt32();
            break;
          }
          case 29: {

            hoursBooked_ = input.readFloat();
            break;
          }
          case 32: {

            dayBooked_ = input.readInt32();
            break;
          }
          case 40: {

            monthBooked_ = input.readInt32();
            break;
          }
          case 48: {

            yearBooked_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.CA1.AutomatedSchedulingApp.ASAServiceImpl.internal_static_absenceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.CA1.AutomatedSchedulingApp.ASAServiceImpl.internal_static_absenceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.CA1.AutomatedSchedulingApp.absenceRequest.class, grpc.CA1.AutomatedSchedulingApp.absenceRequest.Builder.class);
  }

  public static final int CARD_NUMBER_FIELD_NUMBER = 1;
  private int cardNumber_;
  /**
   * <code>int32 card_number = 1;</code>
   */
  public int getCardNumber() {
    return cardNumber_;
  }

  public static final int JOB_NUMBER_FIELD_NUMBER = 2;
  private int jobNumber_;
  /**
   * <code>int32 job_number = 2;</code>
   */
  public int getJobNumber() {
    return jobNumber_;
  }

  public static final int HOURS_BOOKED_FIELD_NUMBER = 3;
  private float hoursBooked_;
  /**
   * <code>float hours_booked = 3;</code>
   */
  public float getHoursBooked() {
    return hoursBooked_;
  }

  public static final int DAY_BOOKED_FIELD_NUMBER = 4;
  private int dayBooked_;
  /**
   * <code>int32 day_booked = 4;</code>
   */
  public int getDayBooked() {
    return dayBooked_;
  }

  public static final int MONTH_BOOKED_FIELD_NUMBER = 5;
  private int monthBooked_;
  /**
   * <code>int32 month_booked = 5;</code>
   */
  public int getMonthBooked() {
    return monthBooked_;
  }

  public static final int YEAR_BOOKED_FIELD_NUMBER = 6;
  private int yearBooked_;
  /**
   * <code>int32 year_booked = 6;</code>
   */
  public int getYearBooked() {
    return yearBooked_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cardNumber_ != 0) {
      output.writeInt32(1, cardNumber_);
    }
    if (jobNumber_ != 0) {
      output.writeInt32(2, jobNumber_);
    }
    if (hoursBooked_ != 0F) {
      output.writeFloat(3, hoursBooked_);
    }
    if (dayBooked_ != 0) {
      output.writeInt32(4, dayBooked_);
    }
    if (monthBooked_ != 0) {
      output.writeInt32(5, monthBooked_);
    }
    if (yearBooked_ != 0) {
      output.writeInt32(6, yearBooked_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cardNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, cardNumber_);
    }
    if (jobNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, jobNumber_);
    }
    if (hoursBooked_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, hoursBooked_);
    }
    if (dayBooked_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, dayBooked_);
    }
    if (monthBooked_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, monthBooked_);
    }
    if (yearBooked_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, yearBooked_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.CA1.AutomatedSchedulingApp.absenceRequest)) {
      return super.equals(obj);
    }
    grpc.CA1.AutomatedSchedulingApp.absenceRequest other = (grpc.CA1.AutomatedSchedulingApp.absenceRequest) obj;

    boolean result = true;
    result = result && (getCardNumber()
        == other.getCardNumber());
    result = result && (getJobNumber()
        == other.getJobNumber());
    result = result && (
        java.lang.Float.floatToIntBits(getHoursBooked())
        == java.lang.Float.floatToIntBits(
            other.getHoursBooked()));
    result = result && (getDayBooked()
        == other.getDayBooked());
    result = result && (getMonthBooked()
        == other.getMonthBooked());
    result = result && (getYearBooked()
        == other.getYearBooked());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARD_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCardNumber();
    hash = (37 * hash) + JOB_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getJobNumber();
    hash = (37 * hash) + HOURS_BOOKED_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHoursBooked());
    hash = (37 * hash) + DAY_BOOKED_FIELD_NUMBER;
    hash = (53 * hash) + getDayBooked();
    hash = (37 * hash) + MONTH_BOOKED_FIELD_NUMBER;
    hash = (53 * hash) + getMonthBooked();
    hash = (37 * hash) + YEAR_BOOKED_FIELD_NUMBER;
    hash = (53 * hash) + getYearBooked();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.CA1.AutomatedSchedulingApp.absenceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code absenceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:absenceRequest)
      grpc.CA1.AutomatedSchedulingApp.absenceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.CA1.AutomatedSchedulingApp.ASAServiceImpl.internal_static_absenceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.CA1.AutomatedSchedulingApp.ASAServiceImpl.internal_static_absenceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.CA1.AutomatedSchedulingApp.absenceRequest.class, grpc.CA1.AutomatedSchedulingApp.absenceRequest.Builder.class);
    }

    // Construct using grpc.CA1.AutomatedSchedulingApp.absenceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cardNumber_ = 0;

      jobNumber_ = 0;

      hoursBooked_ = 0F;

      dayBooked_ = 0;

      monthBooked_ = 0;

      yearBooked_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.CA1.AutomatedSchedulingApp.ASAServiceImpl.internal_static_absenceRequest_descriptor;
    }

    @java.lang.Override
    public grpc.CA1.AutomatedSchedulingApp.absenceRequest getDefaultInstanceForType() {
      return grpc.CA1.AutomatedSchedulingApp.absenceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.CA1.AutomatedSchedulingApp.absenceRequest build() {
      grpc.CA1.AutomatedSchedulingApp.absenceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.CA1.AutomatedSchedulingApp.absenceRequest buildPartial() {
      grpc.CA1.AutomatedSchedulingApp.absenceRequest result = new grpc.CA1.AutomatedSchedulingApp.absenceRequest(this);
      result.cardNumber_ = cardNumber_;
      result.jobNumber_ = jobNumber_;
      result.hoursBooked_ = hoursBooked_;
      result.dayBooked_ = dayBooked_;
      result.monthBooked_ = monthBooked_;
      result.yearBooked_ = yearBooked_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.CA1.AutomatedSchedulingApp.absenceRequest) {
        return mergeFrom((grpc.CA1.AutomatedSchedulingApp.absenceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.CA1.AutomatedSchedulingApp.absenceRequest other) {
      if (other == grpc.CA1.AutomatedSchedulingApp.absenceRequest.getDefaultInstance()) return this;
      if (other.getCardNumber() != 0) {
        setCardNumber(other.getCardNumber());
      }
      if (other.getJobNumber() != 0) {
        setJobNumber(other.getJobNumber());
      }
      if (other.getHoursBooked() != 0F) {
        setHoursBooked(other.getHoursBooked());
      }
      if (other.getDayBooked() != 0) {
        setDayBooked(other.getDayBooked());
      }
      if (other.getMonthBooked() != 0) {
        setMonthBooked(other.getMonthBooked());
      }
      if (other.getYearBooked() != 0) {
        setYearBooked(other.getYearBooked());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.CA1.AutomatedSchedulingApp.absenceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.CA1.AutomatedSchedulingApp.absenceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int cardNumber_ ;
    /**
     * <code>int32 card_number = 1;</code>
     */
    public int getCardNumber() {
      return cardNumber_;
    }
    /**
     * <code>int32 card_number = 1;</code>
     */
    public Builder setCardNumber(int value) {
      
      cardNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 card_number = 1;</code>
     */
    public Builder clearCardNumber() {
      
      cardNumber_ = 0;
      onChanged();
      return this;
    }

    private int jobNumber_ ;
    /**
     * <code>int32 job_number = 2;</code>
     */
    public int getJobNumber() {
      return jobNumber_;
    }
    /**
     * <code>int32 job_number = 2;</code>
     */
    public Builder setJobNumber(int value) {
      
      jobNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 job_number = 2;</code>
     */
    public Builder clearJobNumber() {
      
      jobNumber_ = 0;
      onChanged();
      return this;
    }

    private float hoursBooked_ ;
    /**
     * <code>float hours_booked = 3;</code>
     */
    public float getHoursBooked() {
      return hoursBooked_;
    }
    /**
     * <code>float hours_booked = 3;</code>
     */
    public Builder setHoursBooked(float value) {
      
      hoursBooked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float hours_booked = 3;</code>
     */
    public Builder clearHoursBooked() {
      
      hoursBooked_ = 0F;
      onChanged();
      return this;
    }

    private int dayBooked_ ;
    /**
     * <code>int32 day_booked = 4;</code>
     */
    public int getDayBooked() {
      return dayBooked_;
    }
    /**
     * <code>int32 day_booked = 4;</code>
     */
    public Builder setDayBooked(int value) {
      
      dayBooked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 day_booked = 4;</code>
     */
    public Builder clearDayBooked() {
      
      dayBooked_ = 0;
      onChanged();
      return this;
    }

    private int monthBooked_ ;
    /**
     * <code>int32 month_booked = 5;</code>
     */
    public int getMonthBooked() {
      return monthBooked_;
    }
    /**
     * <code>int32 month_booked = 5;</code>
     */
    public Builder setMonthBooked(int value) {
      
      monthBooked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 month_booked = 5;</code>
     */
    public Builder clearMonthBooked() {
      
      monthBooked_ = 0;
      onChanged();
      return this;
    }

    private int yearBooked_ ;
    /**
     * <code>int32 year_booked = 6;</code>
     */
    public int getYearBooked() {
      return yearBooked_;
    }
    /**
     * <code>int32 year_booked = 6;</code>
     */
    public Builder setYearBooked(int value) {
      
      yearBooked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 year_booked = 6;</code>
     */
    public Builder clearYearBooked() {
      
      yearBooked_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:absenceRequest)
  }

  // @@protoc_insertion_point(class_scope:absenceRequest)
  private static final grpc.CA1.AutomatedSchedulingApp.absenceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.CA1.AutomatedSchedulingApp.absenceRequest();
  }

  public static grpc.CA1.AutomatedSchedulingApp.absenceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<absenceRequest>
      PARSER = new com.google.protobuf.AbstractParser<absenceRequest>() {
    @java.lang.Override
    public absenceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new absenceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<absenceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<absenceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.CA1.AutomatedSchedulingApp.absenceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

