// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package grpc.CA1.AutomatedSchedulingApp;

public interface TaskSpecificationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TaskSpecifications)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string project_number = 1;</code>
   */
  java.lang.String getProjectNumber();
  /**
   * <code>string project_number = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectNumberBytes();

  /**
   * <code>string task = 2;</code>
   */
  java.lang.String getTask();
  /**
   * <code>string task = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaskBytes();

  /**
   * <code>float number_hours = 3;</code>
   */
  float getNumberHours();

  /**
   * <code>int64 day_milestone = 4;</code>
   */
  long getDayMilestone();

  /**
   * <code>int64 month_milestone = 5;</code>
   */
  long getMonthMilestone();

  /**
   * <code>int64 year_milestone = 6;</code>
   */
  long getYearMilestone();
}
