// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package grpc.CA1.AutomatedSchedulingApp;

public interface WorkerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ProjectNumber = 1;</code>
   */
  java.lang.String getProjectNumber();
  /**
   * <code>string ProjectNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectNumberBytes();

  /**
   * <code>string TaskName = 2;</code>
   */
  java.lang.String getTaskName();
  /**
   * <code>string TaskName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaskNameBytes();

  /**
   * <code>string TaskDescription = 3;</code>
   */
  java.lang.String getTaskDescription();
  /**
   * <code>string TaskDescription = 3;</code>
   */
  com.google.protobuf.ByteString
      getTaskDescriptionBytes();

  /**
   * <code>int64 Date = 4;</code>
   */
  long getDate();

  /**
   * <code>float Hours = 5;</code>
   */
  float getHours();

  /**
   * <code>string CardNumber = 6;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string CardNumber = 6;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();
}
