// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailNotification.proto

package EmailsNotifications;

public interface answerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:answer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool Confirmation_Refusal = 1;</code>
   */
  boolean getConfirmationRefusal();
}
