// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package ProjectManager;

public final class projectManagerSchedule {
  private projectManagerSchedule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskSpecifications_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskSpecifications_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TaskMatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TaskMatch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ProjectManagerSchedule.proto\"\230\001\n\022TaskS" +
      "pecifications\022\026\n\016project_number\030\001 \001(\t\022\014\n" +
      "\004task\030\002 \001(\t\022\024\n\014number_hours\030\003 \001(\002\022\025\n\rday" +
      "_milestone\030\004 \001(\003\022\027\n\017month_milestone\030\005 \001(" +
      "\003\022\026\n\016year_milestone\030\006 \001(\003\"G\n\tTaskMatch\022\014" +
      "\n\004date\030\001 \001(\003\022\027\n\017number_of_hours\030\002 \001(\002\022\023\n" +
      "\013card_number\030\003 \001(\t2B\n\016FindingWorkers\0220\n\013" +
      "TaskFinding\022\023.TaskSpecifications\032\n.TaskM" +
      "atch\"\000B*\n\016ProjectManagerB\026projectManager" +
      "ScheduleP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TaskSpecifications_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TaskSpecifications_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskSpecifications_descriptor,
        new java.lang.String[] { "ProjectNumber", "Task", "NumberHours", "DayMilestone", "MonthMilestone", "YearMilestone", });
    internal_static_TaskMatch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TaskMatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TaskMatch_descriptor,
        new java.lang.String[] { "Date", "NumberOfHours", "CardNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
