// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package ProjectManager;

/**
 * Protobuf type {@code taskMatch}
 */
public  final class taskMatch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:taskMatch)
    taskMatchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use taskMatch.newBuilder() to construct.
  private taskMatch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private taskMatch() {
    workingDay_ = 0L;
    workingMonth_ = 0L;
    workingYear_ = 0L;
    date_ = 0L;
    numberOfHours_ = 0F;
    cardNumber_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private taskMatch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            workingDay_ = input.readInt64();
            break;
          }
          case 16: {

            workingMonth_ = input.readInt64();
            break;
          }
          case 24: {

            workingYear_ = input.readInt64();
            break;
          }
          case 32: {

            date_ = input.readInt64();
            break;
          }
          case 45: {

            numberOfHours_ = input.readFloat();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            cardNumber_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProjectManager.projectManagerSchedule.internal_static_taskMatch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProjectManager.projectManagerSchedule.internal_static_taskMatch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProjectManager.taskMatch.class, ProjectManager.taskMatch.Builder.class);
  }

  public static final int WORKING_DAY_FIELD_NUMBER = 1;
  private long workingDay_;
  /**
   * <code>int64 working_day = 1;</code>
   */
  public long getWorkingDay() {
    return workingDay_;
  }

  public static final int WORKING_MONTH_FIELD_NUMBER = 2;
  private long workingMonth_;
  /**
   * <code>int64 working_month = 2;</code>
   */
  public long getWorkingMonth() {
    return workingMonth_;
  }

  public static final int WORKING_YEAR_FIELD_NUMBER = 3;
  private long workingYear_;
  /**
   * <code>int64 working_year = 3;</code>
   */
  public long getWorkingYear() {
    return workingYear_;
  }

  public static final int DATE_FIELD_NUMBER = 4;
  private long date_;
  /**
   * <code>int64 date = 4;</code>
   */
  public long getDate() {
    return date_;
  }

  public static final int NUMBER_OF_HOURS_FIELD_NUMBER = 5;
  private float numberOfHours_;
  /**
   * <code>float number_of_hours = 5;</code>
   */
  public float getNumberOfHours() {
    return numberOfHours_;
  }

  public static final int CARD_NUMBER_FIELD_NUMBER = 6;
  private volatile java.lang.Object cardNumber_;
  /**
   * <code>string card_number = 6;</code>
   */
  public java.lang.String getCardNumber() {
    java.lang.Object ref = cardNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string card_number = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCardNumberBytes() {
    java.lang.Object ref = cardNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (workingDay_ != 0L) {
      output.writeInt64(1, workingDay_);
    }
    if (workingMonth_ != 0L) {
      output.writeInt64(2, workingMonth_);
    }
    if (workingYear_ != 0L) {
      output.writeInt64(3, workingYear_);
    }
    if (date_ != 0L) {
      output.writeInt64(4, date_);
    }
    if (numberOfHours_ != 0F) {
      output.writeFloat(5, numberOfHours_);
    }
    if (!getCardNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cardNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (workingDay_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, workingDay_);
    }
    if (workingMonth_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, workingMonth_);
    }
    if (workingYear_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, workingYear_);
    }
    if (date_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, date_);
    }
    if (numberOfHours_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, numberOfHours_);
    }
    if (!getCardNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cardNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ProjectManager.taskMatch)) {
      return super.equals(obj);
    }
    ProjectManager.taskMatch other = (ProjectManager.taskMatch) obj;

    boolean result = true;
    result = result && (getWorkingDay()
        == other.getWorkingDay());
    result = result && (getWorkingMonth()
        == other.getWorkingMonth());
    result = result && (getWorkingYear()
        == other.getWorkingYear());
    result = result && (getDate()
        == other.getDate());
    result = result && (
        java.lang.Float.floatToIntBits(getNumberOfHours())
        == java.lang.Float.floatToIntBits(
            other.getNumberOfHours()));
    result = result && getCardNumber()
        .equals(other.getCardNumber());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WORKING_DAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWorkingDay());
    hash = (37 * hash) + WORKING_MONTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWorkingMonth());
    hash = (37 * hash) + WORKING_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getWorkingYear());
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDate());
    hash = (37 * hash) + NUMBER_OF_HOURS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getNumberOfHours());
    hash = (37 * hash) + CARD_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCardNumber().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ProjectManager.taskMatch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProjectManager.taskMatch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProjectManager.taskMatch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProjectManager.taskMatch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProjectManager.taskMatch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProjectManager.taskMatch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProjectManager.taskMatch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProjectManager.taskMatch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProjectManager.taskMatch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ProjectManager.taskMatch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProjectManager.taskMatch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProjectManager.taskMatch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ProjectManager.taskMatch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code taskMatch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:taskMatch)
      ProjectManager.taskMatchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProjectManager.projectManagerSchedule.internal_static_taskMatch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProjectManager.projectManagerSchedule.internal_static_taskMatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProjectManager.taskMatch.class, ProjectManager.taskMatch.Builder.class);
    }

    // Construct using ProjectManager.taskMatch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      workingDay_ = 0L;

      workingMonth_ = 0L;

      workingYear_ = 0L;

      date_ = 0L;

      numberOfHours_ = 0F;

      cardNumber_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProjectManager.projectManagerSchedule.internal_static_taskMatch_descriptor;
    }

    @java.lang.Override
    public ProjectManager.taskMatch getDefaultInstanceForType() {
      return ProjectManager.taskMatch.getDefaultInstance();
    }

    @java.lang.Override
    public ProjectManager.taskMatch build() {
      ProjectManager.taskMatch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ProjectManager.taskMatch buildPartial() {
      ProjectManager.taskMatch result = new ProjectManager.taskMatch(this);
      result.workingDay_ = workingDay_;
      result.workingMonth_ = workingMonth_;
      result.workingYear_ = workingYear_;
      result.date_ = date_;
      result.numberOfHours_ = numberOfHours_;
      result.cardNumber_ = cardNumber_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProjectManager.taskMatch) {
        return mergeFrom((ProjectManager.taskMatch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProjectManager.taskMatch other) {
      if (other == ProjectManager.taskMatch.getDefaultInstance()) return this;
      if (other.getWorkingDay() != 0L) {
        setWorkingDay(other.getWorkingDay());
      }
      if (other.getWorkingMonth() != 0L) {
        setWorkingMonth(other.getWorkingMonth());
      }
      if (other.getWorkingYear() != 0L) {
        setWorkingYear(other.getWorkingYear());
      }
      if (other.getDate() != 0L) {
        setDate(other.getDate());
      }
      if (other.getNumberOfHours() != 0F) {
        setNumberOfHours(other.getNumberOfHours());
      }
      if (!other.getCardNumber().isEmpty()) {
        cardNumber_ = other.cardNumber_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ProjectManager.taskMatch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ProjectManager.taskMatch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long workingDay_ ;
    /**
     * <code>int64 working_day = 1;</code>
     */
    public long getWorkingDay() {
      return workingDay_;
    }
    /**
     * <code>int64 working_day = 1;</code>
     */
    public Builder setWorkingDay(long value) {
      
      workingDay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 working_day = 1;</code>
     */
    public Builder clearWorkingDay() {
      
      workingDay_ = 0L;
      onChanged();
      return this;
    }

    private long workingMonth_ ;
    /**
     * <code>int64 working_month = 2;</code>
     */
    public long getWorkingMonth() {
      return workingMonth_;
    }
    /**
     * <code>int64 working_month = 2;</code>
     */
    public Builder setWorkingMonth(long value) {
      
      workingMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 working_month = 2;</code>
     */
    public Builder clearWorkingMonth() {
      
      workingMonth_ = 0L;
      onChanged();
      return this;
    }

    private long workingYear_ ;
    /**
     * <code>int64 working_year = 3;</code>
     */
    public long getWorkingYear() {
      return workingYear_;
    }
    /**
     * <code>int64 working_year = 3;</code>
     */
    public Builder setWorkingYear(long value) {
      
      workingYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 working_year = 3;</code>
     */
    public Builder clearWorkingYear() {
      
      workingYear_ = 0L;
      onChanged();
      return this;
    }

    private long date_ ;
    /**
     * <code>int64 date = 4;</code>
     */
    public long getDate() {
      return date_;
    }
    /**
     * <code>int64 date = 4;</code>
     */
    public Builder setDate(long value) {
      
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 date = 4;</code>
     */
    public Builder clearDate() {
      
      date_ = 0L;
      onChanged();
      return this;
    }

    private float numberOfHours_ ;
    /**
     * <code>float number_of_hours = 5;</code>
     */
    public float getNumberOfHours() {
      return numberOfHours_;
    }
    /**
     * <code>float number_of_hours = 5;</code>
     */
    public Builder setNumberOfHours(float value) {
      
      numberOfHours_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float number_of_hours = 5;</code>
     */
    public Builder clearNumberOfHours() {
      
      numberOfHours_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object cardNumber_ = "";
    /**
     * <code>string card_number = 6;</code>
     */
    public java.lang.String getCardNumber() {
      java.lang.Object ref = cardNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string card_number = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCardNumberBytes() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string card_number = 6;</code>
     */
    public Builder setCardNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string card_number = 6;</code>
     */
    public Builder clearCardNumber() {
      
      cardNumber_ = getDefaultInstance().getCardNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string card_number = 6;</code>
     */
    public Builder setCardNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardNumber_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:taskMatch)
  }

  // @@protoc_insertion_point(class_scope:taskMatch)
  private static final ProjectManager.taskMatch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProjectManager.taskMatch();
  }

  public static ProjectManager.taskMatch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<taskMatch>
      PARSER = new com.google.protobuf.AbstractParser<taskMatch>() {
    @java.lang.Override
    public taskMatch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new taskMatch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<taskMatch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<taskMatch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ProjectManager.taskMatch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

