// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package ProjectManager;

public interface TaskMatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TaskMatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 date = 1;</code>
   */
  long getDate();

  /**
   * <code>float number_of_hours = 2;</code>
   */
  float getNumberOfHours();

  /**
   * <code>string card_number = 3;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string card_number = 3;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();
}
