// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package ProjectManager;

public interface TaskSpecificationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TaskSpecifications)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string project_number = 1;</code>
   */
  java.lang.String getProjectNumber();
  /**
   * <code>string project_number = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectNumberBytes();

  /**
   * <code>string task = 2;</code>
   */
  java.lang.String getTask();
  /**
   * <code>string task = 2;</code>
   */
  com.google.protobuf.ByteString
      getTaskBytes();

  /**
   * <code>float number_hours = 3;</code>
   */
  float getNumberHours();

  /**
   * <code>int64 start_day = 4;</code>
   */
  long getStartDay();

  /**
   * <code>int64 start_month = 5;</code>
   */
  long getStartMonth();

  /**
   * <code>int64 start_year = 6;</code>
   */
  long getStartYear();

  /**
   * <code>int64 milestone_day = 7;</code>
   */
  long getMilestoneDay();

  /**
   * <code>int64 milestone_month = 8;</code>
   */
  long getMilestoneMonth();

  /**
   * <code>int64 milestone_year = 9;</code>
   */
  long getMilestoneYear();
}
