// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProjectManagerSchedule.proto

package ProjectManager;

/**
 * Protobuf type {@code TaskSpecifications}
 */
public  final class TaskSpecifications extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TaskSpecifications)
    TaskSpecificationsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskSpecifications.newBuilder() to construct.
  private TaskSpecifications(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskSpecifications() {
    projectNumber_ = "";
    task_ = "";
    numberHours_ = 0F;
    startDay_ = 0L;
    startMonth_ = 0L;
    startYear_ = 0L;
    milestoneDay_ = 0L;
    milestoneMonth_ = 0L;
    milestoneYear_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskSpecifications(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            projectNumber_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            task_ = s;
            break;
          }
          case 29: {

            numberHours_ = input.readFloat();
            break;
          }
          case 32: {

            startDay_ = input.readInt64();
            break;
          }
          case 40: {

            startMonth_ = input.readInt64();
            break;
          }
          case 48: {

            startYear_ = input.readInt64();
            break;
          }
          case 56: {

            milestoneDay_ = input.readInt64();
            break;
          }
          case 64: {

            milestoneMonth_ = input.readInt64();
            break;
          }
          case 72: {

            milestoneYear_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProjectManager.projectManagerSchedule.internal_static_TaskSpecifications_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProjectManager.projectManagerSchedule.internal_static_TaskSpecifications_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProjectManager.TaskSpecifications.class, ProjectManager.TaskSpecifications.Builder.class);
  }

  public static final int PROJECT_NUMBER_FIELD_NUMBER = 1;
  private volatile java.lang.Object projectNumber_;
  /**
   * <code>string project_number = 1;</code>
   */
  public java.lang.String getProjectNumber() {
    java.lang.Object ref = projectNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string project_number = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProjectNumberBytes() {
    java.lang.Object ref = projectNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASK_FIELD_NUMBER = 2;
  private volatile java.lang.Object task_;
  /**
   * <code>string task = 2;</code>
   */
  public java.lang.String getTask() {
    java.lang.Object ref = task_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      task_ = s;
      return s;
    }
  }
  /**
   * <code>string task = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTaskBytes() {
    java.lang.Object ref = task_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      task_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMBER_HOURS_FIELD_NUMBER = 3;
  private float numberHours_;
  /**
   * <code>float number_hours = 3;</code>
   */
  public float getNumberHours() {
    return numberHours_;
  }

  public static final int START_DAY_FIELD_NUMBER = 4;
  private long startDay_;
  /**
   * <code>int64 start_day = 4;</code>
   */
  public long getStartDay() {
    return startDay_;
  }

  public static final int START_MONTH_FIELD_NUMBER = 5;
  private long startMonth_;
  /**
   * <code>int64 start_month = 5;</code>
   */
  public long getStartMonth() {
    return startMonth_;
  }

  public static final int START_YEAR_FIELD_NUMBER = 6;
  private long startYear_;
  /**
   * <code>int64 start_year = 6;</code>
   */
  public long getStartYear() {
    return startYear_;
  }

  public static final int MILESTONE_DAY_FIELD_NUMBER = 7;
  private long milestoneDay_;
  /**
   * <code>int64 milestone_day = 7;</code>
   */
  public long getMilestoneDay() {
    return milestoneDay_;
  }

  public static final int MILESTONE_MONTH_FIELD_NUMBER = 8;
  private long milestoneMonth_;
  /**
   * <code>int64 milestone_month = 8;</code>
   */
  public long getMilestoneMonth() {
    return milestoneMonth_;
  }

  public static final int MILESTONE_YEAR_FIELD_NUMBER = 9;
  private long milestoneYear_;
  /**
   * <code>int64 milestone_year = 9;</code>
   */
  public long getMilestoneYear() {
    return milestoneYear_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProjectNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, projectNumber_);
    }
    if (!getTaskBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, task_);
    }
    if (numberHours_ != 0F) {
      output.writeFloat(3, numberHours_);
    }
    if (startDay_ != 0L) {
      output.writeInt64(4, startDay_);
    }
    if (startMonth_ != 0L) {
      output.writeInt64(5, startMonth_);
    }
    if (startYear_ != 0L) {
      output.writeInt64(6, startYear_);
    }
    if (milestoneDay_ != 0L) {
      output.writeInt64(7, milestoneDay_);
    }
    if (milestoneMonth_ != 0L) {
      output.writeInt64(8, milestoneMonth_);
    }
    if (milestoneYear_ != 0L) {
      output.writeInt64(9, milestoneYear_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProjectNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, projectNumber_);
    }
    if (!getTaskBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, task_);
    }
    if (numberHours_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, numberHours_);
    }
    if (startDay_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, startDay_);
    }
    if (startMonth_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, startMonth_);
    }
    if (startYear_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, startYear_);
    }
    if (milestoneDay_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, milestoneDay_);
    }
    if (milestoneMonth_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, milestoneMonth_);
    }
    if (milestoneYear_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, milestoneYear_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ProjectManager.TaskSpecifications)) {
      return super.equals(obj);
    }
    ProjectManager.TaskSpecifications other = (ProjectManager.TaskSpecifications) obj;

    boolean result = true;
    result = result && getProjectNumber()
        .equals(other.getProjectNumber());
    result = result && getTask()
        .equals(other.getTask());
    result = result && (
        java.lang.Float.floatToIntBits(getNumberHours())
        == java.lang.Float.floatToIntBits(
            other.getNumberHours()));
    result = result && (getStartDay()
        == other.getStartDay());
    result = result && (getStartMonth()
        == other.getStartMonth());
    result = result && (getStartYear()
        == other.getStartYear());
    result = result && (getMilestoneDay()
        == other.getMilestoneDay());
    result = result && (getMilestoneMonth()
        == other.getMilestoneMonth());
    result = result && (getMilestoneYear()
        == other.getMilestoneYear());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROJECT_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getProjectNumber().hashCode();
    hash = (37 * hash) + TASK_FIELD_NUMBER;
    hash = (53 * hash) + getTask().hashCode();
    hash = (37 * hash) + NUMBER_HOURS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getNumberHours());
    hash = (37 * hash) + START_DAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartDay());
    hash = (37 * hash) + START_MONTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartMonth());
    hash = (37 * hash) + START_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartYear());
    hash = (37 * hash) + MILESTONE_DAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMilestoneDay());
    hash = (37 * hash) + MILESTONE_MONTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMilestoneMonth());
    hash = (37 * hash) + MILESTONE_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMilestoneYear());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ProjectManager.TaskSpecifications parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProjectManager.TaskSpecifications parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProjectManager.TaskSpecifications parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProjectManager.TaskSpecifications parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProjectManager.TaskSpecifications parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProjectManager.TaskSpecifications parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProjectManager.TaskSpecifications parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProjectManager.TaskSpecifications parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProjectManager.TaskSpecifications parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ProjectManager.TaskSpecifications parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProjectManager.TaskSpecifications parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProjectManager.TaskSpecifications parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ProjectManager.TaskSpecifications prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TaskSpecifications}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TaskSpecifications)
      ProjectManager.TaskSpecificationsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProjectManager.projectManagerSchedule.internal_static_TaskSpecifications_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProjectManager.projectManagerSchedule.internal_static_TaskSpecifications_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProjectManager.TaskSpecifications.class, ProjectManager.TaskSpecifications.Builder.class);
    }

    // Construct using ProjectManager.TaskSpecifications.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      projectNumber_ = "";

      task_ = "";

      numberHours_ = 0F;

      startDay_ = 0L;

      startMonth_ = 0L;

      startYear_ = 0L;

      milestoneDay_ = 0L;

      milestoneMonth_ = 0L;

      milestoneYear_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProjectManager.projectManagerSchedule.internal_static_TaskSpecifications_descriptor;
    }

    @java.lang.Override
    public ProjectManager.TaskSpecifications getDefaultInstanceForType() {
      return ProjectManager.TaskSpecifications.getDefaultInstance();
    }

    @java.lang.Override
    public ProjectManager.TaskSpecifications build() {
      ProjectManager.TaskSpecifications result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ProjectManager.TaskSpecifications buildPartial() {
      ProjectManager.TaskSpecifications result = new ProjectManager.TaskSpecifications(this);
      result.projectNumber_ = projectNumber_;
      result.task_ = task_;
      result.numberHours_ = numberHours_;
      result.startDay_ = startDay_;
      result.startMonth_ = startMonth_;
      result.startYear_ = startYear_;
      result.milestoneDay_ = milestoneDay_;
      result.milestoneMonth_ = milestoneMonth_;
      result.milestoneYear_ = milestoneYear_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProjectManager.TaskSpecifications) {
        return mergeFrom((ProjectManager.TaskSpecifications)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProjectManager.TaskSpecifications other) {
      if (other == ProjectManager.TaskSpecifications.getDefaultInstance()) return this;
      if (!other.getProjectNumber().isEmpty()) {
        projectNumber_ = other.projectNumber_;
        onChanged();
      }
      if (!other.getTask().isEmpty()) {
        task_ = other.task_;
        onChanged();
      }
      if (other.getNumberHours() != 0F) {
        setNumberHours(other.getNumberHours());
      }
      if (other.getStartDay() != 0L) {
        setStartDay(other.getStartDay());
      }
      if (other.getStartMonth() != 0L) {
        setStartMonth(other.getStartMonth());
      }
      if (other.getStartYear() != 0L) {
        setStartYear(other.getStartYear());
      }
      if (other.getMilestoneDay() != 0L) {
        setMilestoneDay(other.getMilestoneDay());
      }
      if (other.getMilestoneMonth() != 0L) {
        setMilestoneMonth(other.getMilestoneMonth());
      }
      if (other.getMilestoneYear() != 0L) {
        setMilestoneYear(other.getMilestoneYear());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ProjectManager.TaskSpecifications parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ProjectManager.TaskSpecifications) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object projectNumber_ = "";
    /**
     * <code>string project_number = 1;</code>
     */
    public java.lang.String getProjectNumber() {
      java.lang.Object ref = projectNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string project_number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProjectNumberBytes() {
      java.lang.Object ref = projectNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string project_number = 1;</code>
     */
    public Builder setProjectNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string project_number = 1;</code>
     */
    public Builder clearProjectNumber() {
      
      projectNumber_ = getDefaultInstance().getProjectNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string project_number = 1;</code>
     */
    public Builder setProjectNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object task_ = "";
    /**
     * <code>string task = 2;</code>
     */
    public java.lang.String getTask() {
      java.lang.Object ref = task_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        task_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskBytes() {
      java.lang.Object ref = task_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        task_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task = 2;</code>
     */
    public Builder setTask(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      task_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task = 2;</code>
     */
    public Builder clearTask() {
      
      task_ = getDefaultInstance().getTask();
      onChanged();
      return this;
    }
    /**
     * <code>string task = 2;</code>
     */
    public Builder setTaskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      task_ = value;
      onChanged();
      return this;
    }

    private float numberHours_ ;
    /**
     * <code>float number_hours = 3;</code>
     */
    public float getNumberHours() {
      return numberHours_;
    }
    /**
     * <code>float number_hours = 3;</code>
     */
    public Builder setNumberHours(float value) {
      
      numberHours_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float number_hours = 3;</code>
     */
    public Builder clearNumberHours() {
      
      numberHours_ = 0F;
      onChanged();
      return this;
    }

    private long startDay_ ;
    /**
     * <code>int64 start_day = 4;</code>
     */
    public long getStartDay() {
      return startDay_;
    }
    /**
     * <code>int64 start_day = 4;</code>
     */
    public Builder setStartDay(long value) {
      
      startDay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start_day = 4;</code>
     */
    public Builder clearStartDay() {
      
      startDay_ = 0L;
      onChanged();
      return this;
    }

    private long startMonth_ ;
    /**
     * <code>int64 start_month = 5;</code>
     */
    public long getStartMonth() {
      return startMonth_;
    }
    /**
     * <code>int64 start_month = 5;</code>
     */
    public Builder setStartMonth(long value) {
      
      startMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start_month = 5;</code>
     */
    public Builder clearStartMonth() {
      
      startMonth_ = 0L;
      onChanged();
      return this;
    }

    private long startYear_ ;
    /**
     * <code>int64 start_year = 6;</code>
     */
    public long getStartYear() {
      return startYear_;
    }
    /**
     * <code>int64 start_year = 6;</code>
     */
    public Builder setStartYear(long value) {
      
      startYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start_year = 6;</code>
     */
    public Builder clearStartYear() {
      
      startYear_ = 0L;
      onChanged();
      return this;
    }

    private long milestoneDay_ ;
    /**
     * <code>int64 milestone_day = 7;</code>
     */
    public long getMilestoneDay() {
      return milestoneDay_;
    }
    /**
     * <code>int64 milestone_day = 7;</code>
     */
    public Builder setMilestoneDay(long value) {
      
      milestoneDay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 milestone_day = 7;</code>
     */
    public Builder clearMilestoneDay() {
      
      milestoneDay_ = 0L;
      onChanged();
      return this;
    }

    private long milestoneMonth_ ;
    /**
     * <code>int64 milestone_month = 8;</code>
     */
    public long getMilestoneMonth() {
      return milestoneMonth_;
    }
    /**
     * <code>int64 milestone_month = 8;</code>
     */
    public Builder setMilestoneMonth(long value) {
      
      milestoneMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 milestone_month = 8;</code>
     */
    public Builder clearMilestoneMonth() {
      
      milestoneMonth_ = 0L;
      onChanged();
      return this;
    }

    private long milestoneYear_ ;
    /**
     * <code>int64 milestone_year = 9;</code>
     */
    public long getMilestoneYear() {
      return milestoneYear_;
    }
    /**
     * <code>int64 milestone_year = 9;</code>
     */
    public Builder setMilestoneYear(long value) {
      
      milestoneYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 milestone_year = 9;</code>
     */
    public Builder clearMilestoneYear() {
      
      milestoneYear_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TaskSpecifications)
  }

  // @@protoc_insertion_point(class_scope:TaskSpecifications)
  private static final ProjectManager.TaskSpecifications DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProjectManager.TaskSpecifications();
  }

  public static ProjectManager.TaskSpecifications getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskSpecifications>
      PARSER = new com.google.protobuf.AbstractParser<TaskSpecifications>() {
    @java.lang.Override
    public TaskSpecifications parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaskSpecifications(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskSpecifications> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskSpecifications> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ProjectManager.TaskSpecifications getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

